version: '3'

services:
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: renatogroffe
  #     ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
  #   links:
  #     - mongo
  #   networks:
  #     - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
